### PR TITLE
Em-dashboard-widgets

### PR DESCRIPTION
**Pull request by erickmoore**
This update adds pictures to the dashboard widget documentation along with configurable settings for each widget. As this data is visual in nature it is important to show the visualizations in our documentation.

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--prisma-cloud-docs--hlxsites.hlx.page/
- After: https://<branch>--prisma-cloud-docs--hlxsites.hlx.page/
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=<branch>

### CODE REVIEW

**Comment by sgordon46** [comment]
@erickmoore Great Job.   This is much needed.

**Comment by erickmoore** [comment]
@jenjoe22 Anyway we can get this fast-tracked as it has been a hot ask from a lot of accounts.

**Comment by jenjoe22** [comment]
> @jenjoe22 Anyway we can get this fast-tracked as it has been a hot ask from a lot of accounts.

@erickmoore Thanks for adding this content. I'll review this with PM.

**Comment by sgordon46** [comment]
@asardar is the PM for the dashboard.

**Comment by jenjoe22** [comment]
> > @jenjoe22 Anyway we can get this fast-tracked as it has been a hot ask from a lot of accounts.
> 
> @erickmoore Thanks for adding this content. I'll review this with PM.

@erickmoore I wanted to provide you a quick update that I'm still working on getting these changes reviewed. I have asked our DocOps team to create a [preview]([https://main--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/content-collections/d[…]/create-and-manage-dashboards?branch=pr-653](https://main--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/content-collections/dashboards/create-and-manage-dashboards?branch=pr-653)). Ashwini from my team is also reviewing these changes with the PM Ali.

**Comment by erickmoore** [comment]
> > > @jenjoe22 Anyway we can get this fast-tracked as it has been a hot ask from a lot of accounts.
> > 
> > 
> > @erickmoore Thanks for adding this content. I'll review this with PM.
> 
> @erickmoore I wanted to provide you a quick update that I'm still working on getting these changes reviewed. I have asked our DocOps team to create a preview. Ashwini from my team is also reviewing these changes with the PM Ali.

Thanks @jenjoe22 ! If I have the ability to create a preview as part of the PR process please let me know as I am happy to make sure I follow the proper procedure.

**Comment by sgordon46** [comment]
@erickmoore I haven't heard anything, we need to move faster then this.

**Comment by erickmoore** [comment]
Closing in favor of this PR: https://github.com/hlxsites/prisma-cloud-docs/pull/704

**Pull request closed without merging**
